[build]
  command = "npm ci --no-optional && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_VERSION = "9.6.7"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NPM_FLAGS = "--no-optional"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm ci --no-optional && npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm ci --no-optional && npm run build"

[context.branch-deploy]
  command = "npm ci --no-optional && npm run build"
